version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=stock_data
      - DB_PORT=5432
      - GROUP_ID=8
    volumes:
      - ./mqtt-client:/app/mqtt-client
    restart: unless-stopped

  mqtt-client:
    build: ./mqtt-client
    depends_on:
      - api
    environment:
      - HOST=broker.iic2173.org
      - PORT=9000
      - USERNAME=students
      - PASSWORD=iic2173-2025-1-students
      - API_URL=http://api:3000/stocks
    restart: unless-stopped

  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=stock_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pg_data: