# boletas-serverless/serverless.yml
service: boletas-pdf-grupo1

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  
  environment:
    BUCKET_NAME: boletas-grupo1-${self:provider.stage}
    GRUPO_NOMBRE: "Grupo 1 - IIC2173"
    STAGE: ${self:provider.stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObject
        - s3:HeadObject
        - s3:ListBucket
      Resource: 
        - "arn:aws:s3:::boletas-grupo1-${self:provider.stage}"
        - "arn:aws:s3:::boletas-grupo1-${self:provider.stage}/*"

functions:
  generateBoleta:
    handler: src/handlers/generateBoleta.handler
    events:
      - http:
          path: /generate-boleta
          method: post
          cors: true
      - http:
          path: /generate-boleta
          method: options
          cors: true
    
  getBoletaStatus:
    handler: src/handlers/generateBoleta.getBoletaStatusHandler
    events:
      - http:
          path: /boleta/{boletaId}
          method: get
          cors: true
                
  healthCheck:
    handler: src/handlers/generateBoleta.healthCheckHandler
    events:
      - http:
          path: /health
          method: get
          cors: true