service: boletas-pdf-grupo1

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    GRUPO_NOMBRE: "Grupo 1 - IIC2173"
    STAGE: ${self:provider.stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucketName}/*"
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::${self:custom.bucketName}"

custom:
  bucketName: boletas-grupo1-${self:provider.stage}

functions:
  generateBoleta:
    handler: src/handlers/generateBoleta.handler
    events:
      - http:
          path: /generate-boleta
          method: post
          cors: true
    
  getBoletaStatus:
    handler: src/handlers/getBoletaStatus.handler
    events:
      - http:
          path: /boleta/{boletaId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                boletaId: true
                
  healthCheck:
    handler: src/handlers/healthCheck.handler
    events:
      - http:
          path: /health
          method: get
          cors: true

resources:
  Resources:
    BoletasBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, HEAD]
              AllowedOrigins: ['*']
              MaxAge: 3000
                
    BoletasBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn: BoletasBucket
      Properties:
        Bucket: !Ref BoletasBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref BoletasBucket
                  - '/boletas/*'

  Outputs:
    ApiGatewayUrl:
      Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
      Export:
        Name: ${self:service}-${self:provider.stage}-ApiGatewayUrl
        
    BoletasBucketName:
      Value: !Ref BoletasBucket
      Export:
        Name: ${self:service}-${self:provider.stage}-BoletasBucketName

plugins:
  - serverless-offline